# Generated by Django 3.0.3 on 2020-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_auto_20200208_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facts',
            name='author',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='facts',
            name='facts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.CharField(max_length=100),
        ),
    ]
